version: "3.3"
services:
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    expose:
      - 6379
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: USERDB
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - my-db:/var/lib/mysql
  api:
    build: .
    environment:
      REDIS_HOST: redis
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - mysql
      - redis
volumes:
  my-db: